### ISSUE TITLE
Pagination routes/deliberations/index.svelte

### ISSUE THREAD

**Issue by WilliamDiakite** [publicarchi/cbc-client-old#6]
Lors d'un changement du nombre de résultat par page, la nouvelle page n'est pas correctement calculée.

**Comment by WilliamDiakite** [comment]
Je pense que le bug vient en fait du code de l'API basex. 

Côté interface, quand la première requête est effectuée (```http://127.0.0.1:8984/cbc/deliberations?start=0&count=20```), les 20 premières délibérations sont retournées par l'API comme prévu.

Quand on change de page (boutton de pagination "page suivante"), une nouvelle requête est effectuée ```http://127.0.0.1:8984/cbc/deliberations?start=20&count=20```. Côté interface on reçoit une erreur avec un status 500, l'erreur mentionne un problème de CORS. Par contre quand cette même requête est lancée avec Postman on reçoit l'erreur suivante :

> Stopped at /Applications/basex/webapp/cbc/cbc.xqm, 216/77:
[XPTY0004] Item expected, sequence found: ("Saint-Denis", "Franciade").

Est-ce que le prblème ne serait pas lié au fait qu'il existe plusieurs noms de commune pour une même délibération ?

**Comment by emchateau** [comment]
solved by 98780196fd9b79bb342a1c8834e8f15e6552e9a2
