### ISSUE TITLE
Créer une fenêtre modale pour le regroupement d’affaires

### ISSUE THREAD

**Issue by emchateau** [publicarchi/cbc-client-old#9]
**Fenêtre modale avec content-switcher (Sélectionner une affaire / Créer une nouvelle affaire)**

### Sélectionner une affaire
- l’api renvoie une liste de propositions d’après la sélection (à partir des ids)
- l’utilisateur peut faire sa propre recherche (nouvelle requête à l’API recherche simple)
- sélectionner une affaire --> bascule dans modifier l’affaire

### Créer une affaire / Modifier l’affaire
- Affichage de la notice
- Liste des délibérations sélectionnées
- Alerte si une délibération est déjà rattachée à une affaire
- valider + confirmation

**Comment by WilliamDiakite** [comment]
Dans le commit du 08/02/2022, j'ai ajouté le modal et fait un exemple des dummy data. Dès que les ressources auront été préparées côté API, je pourrait connecter le client. 

En attendant je continue d'avancer sur la validation du formulaire de création/modification d'une affaire.

**Comment by WilliamDiakite** [comment]
Réglé avec b3f4d368d88987376dc083479d62303fad38394e
